---
title: "AERONET_dust_Analysis"
author: "Meytar Sorek-Hamer"
date: "April 11, 2019"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Libraries
```{r,echo=FALSE,include=FALSE}
library(purrr)
library(tidyr)
library(ggplot2)
library(data.table)
library(dplyr)
library(Hmisc)
library(rlist)
library(xgboost)
library(caret)
```
## Load the working data base
#AERONET AOD + EPA CSN elements for dust
```{r}

#wdb.f<-fread("C:/Users/msorekha/Documents/Projects/JPL/MISR/Data/WDB/AODonly.pm.spec.csv")
#vars <- fread(("C:/Users/msorekha/Documents/Projects/JPL/MISR/Data/WDB/vars.type.spec.csv"))
wdb.s <-fread("/Volumes/GoogleDrive/My Drive/AERONET-MISR/Paper#2-RSoE/aeronet/aeronet/data/inv.spec.data.csv")
#write.csv(names(wdb.s),"/Volumes/GoogleDrive/My Drive/AERONET-MISR/Paper#2-RSoE/aeronet/aeronet/data/inv.vars.spec.csv",row.names = F)
table(wdb.s$`Parameter Name`)
wdb.s <- na_if(wdb.s, "-999")
si <- wdb.s[wdb.s$`Parameter Name` %in% c("Silicon PM2.5 LC"),]
si = si %>% rename(si=value)
al <- wdb.s[wdb.s$`Parameter Name` %in% c("Aluminum PM2.5 LC"),c(1:2,8)]
al = al %>% rename(al=value)
fe <- wdb.s[wdb.s$`Parameter Name` %in% c("Iron PM2.5 LC"),c(1:2,8)]
fe = fe %>% rename(fe=value)
ti <- wdb.s[wdb.s$`Parameter Name` %in% c("Titanium PM2.5 LC"),c(1:2,8)]
ti = ti %>% rename(ti=value)
ca <- wdb.s[wdb.s$`Parameter Name` %in% c("Calcium PM2.5 LC"),c(1:2,8)]
ca = ca %>% rename(ca=value)

wdb.s <- Reduce(inner_join, list(al,si, fe, ti, ca))
wdb.s$dust = 2.2*wdb.s$al+2.49*wdb.s$si+1.63*wdb.s$ca+1.94*wdb.s$ti+2.42*wdb.s$fe

dim(wdb.s)
mean(wdb.s$dust)
sd(wdb.s$dust)

# variables for inv xgboost
vars <- fread("/Volumes/GoogleDrive/My Drive/AERONET-MISR/Paper#2-RSoE/aeronet/aeronet/data/inv.vars.dust.csv")

```

# List Directories
```{r message=FALSE, warning=FALSE, paged.print=FALSE}
#save results
#res_dir <- "C:/Users/msorekha/Documents/Projects/JPL/MISR/plots/Stage2/"
res_dir <- "/Volumes/GoogleDrive/My Drive/AERONET-MISR/Paper#2-RSoE/aeronet/aeronet/results"
```
#XGBoost
```{r,echo=T,results='hide'}
#clean working database to complete cases
dataset <- wdb.f[,c(5:19,62)]
setDF(dataset)
dataset <-Filter(function(x)!all(is.na(x)), dataset )
dataset<-dataset[which(!is.na(dataset$sulfate)),]
setDT(dataset)
#exclude vars with less than 90% availability
dataset <- dataset[,(colSums(is.na(dataset)/dim(dataset)[1]))<0.1,with=FALSE]#423*59 vars
dataset<-dataset[complete.cases(dataset),]#653

#XGBoost
tune_grid <- expand.grid(nrounds = 100,
                         max_depth = 5,
                         eta = 0.05,
                         gamma = 0.01,
                         colsample_bytree = 0.75,
                         min_child_weight = 0,
                         subsample = 0.5)
# Run algorithms using 10-fold cross validation
control <- trainControl(method="cv", number=10,verboseIter=TRUE)

fit.xgb <- train(sulfate~., data=dataset, method = "xgbTree",
                 trControl=control,
                 tuneGrid = tune_grid,
                 tuneLength = 10, importance=TRUE)
#saveRDS(fit.xgb,paste0(res_dir,"fit.xgb.train.rds"))
```
#results
```{r}
print(fit.xgb)

```

##importance of Variables
#interpretation with SHAP-all vars
```{r}
library(xgboost)
source('~/R/Scripts/functions/shap.R')
wdb.na <- setDT(dataset)
#arrange data
names(wdb.na) <- sub("_","",names(wdb.na))
names(wdb.na) <- sub("-","",names(wdb.na))
names(wdb.na) <- sub("[","",names(wdb.na),fixed=TRUE)
names(wdb.na) <- sub("]","",names(wdb.na))
data_2 <- wdb.na[,-c("sulfate")]

data_dmy = dummyVars(" ~ .", data = data_2, fullRank=T)
data_x = predict(data_dmy, newdata = data_2)

## Create the xgboost model
model_xgb = xgboost(data = data_x, 
                   nround = 10, 
                   objective="reg:linear",
                   label= wdb.na$sulfate)  

## Calculate shap values
shap_result = shap.score.rank(xgb_model = model_xgb, 
                              X_train =data_x,
                              shap_approx = F)

# `shap_approx` comes from `approxcontrib` from xgboost documentation. 
# Faster but less accurate if true. Read more: help(xgboost)

## Plot var importance based on SHAP
var_importance(shap_result, top_n=10)

## Prepare data for top N variables
shap_long <- shap.prep(shap = shap_result,
                           X_train = data_x , 
                           top_n = 10)

source('~/R/Scripts/functions/plot.shap.summary.R') #Thanks to Y.LIU (MSSM)
plot.shap.summary(shap_long)#Plot shap overall metrics
tiff(paste0(res_dir,"shap_sulfateAOD_CA.tif"), res = 300)
plot.shap.summary(shap_long)#Plot shap overall metrics
dev.off()

## SHAP plot per variable 
# tiff(paste0(res_dir,"shap1_ca_pervar.tif"))
# xgb.plot.shap(data = data_x, # input data
#               model = model_xgb, # xgboost model
#               features = names(shap_result$mean_shap_score[1:10]), # only top 10 var
#               n_col = 3, # layout option
#               plot_loess = T # add red line to plot
#               )
# dev.off()

# Do some classical plots
#ggplotgui::ggplot_shiny(wdb.na)
```
#AERONET AOD + INV + EPA CSN

## Load the working data base
```{r}
#wdb.f<-fread("C:/Users/msorekha/Documents/Projects/JPL/MISR/Data/WDB/AOD.pm.inv_CA.csv")
# regional subsets
wdb.s.w <-wdb.s[wdb.s$Site_Name %in% c("Fresno_2", "DRAGON_Madera_city", "DRAGON_Tranquility","DRAGON_Bakersfield"),]
dim(wdb.s.w)
mean(wdb.s.w$dust)
sd(wdb.s.w$dust)
wdb.s.c <-wdb.s[wdb.s$Site_Name %in% c("Denver_LaCasa", "DRAGON_Chatfield_Pk"),]
dim(wdb.s.c)
mean(wdb.s.c$dust)
sd(wdb.s.c$dust)
wdb.s.e <-wdb.s[wdb.s$Site_Name %in% c("CCNY","USDA_Howard","DRAGON_PATUX","NASA_LaRC", "EPA-Res_Triangle_Pk", "Georgia_Tech"),]
dim(wdb.s.e)
mean(wdb.s.e$dust)
sd(wdb.s.e$dust)
```

#XGBoost
```{r,echo=T,results='hide'}
#clean working database to complete cases
setDF(wdb.s.e)
dataset <- wdb.s.e[,  names(wdb.s.e)%in%vars$Var1]
#dataset <- cbind(dataset,sulfate=wdb.f$sulfate)
#dataset$PM25<-NULL
#dataset[dataset=='-999']<-NA
#dataset <-Filter(function(x)!all(is.na(x)), dataset )
#dataset<-dataset[which(!is.na(dataset$sulfate)),]
#exclude vars with less than 90% availability
#setDT(dataset)
#dataset <- dataset[,(colSums(is.na(dataset)/dim(dataset)[1]))<0.1,with=FALSE]#423*59 vars
#dataset<-dataset[complete.cases(dataset),]#653

#XGBoost
tune_grid <- expand.grid(nrounds = 100,
                         max_depth = 5,
                         eta = 0.05,
                         gamma = 0.01,
                         colsample_bytree = 0.75,
                         min_child_weight = 0,
                         subsample = 0.5)
# Run algorithms using 10-fold cross validation
control <- trainControl(method="cv", number=10,verboseIter=TRUE)

fit.xgb <- train(dust~., data=dataset, method = "xgbTree",
                 trControl=control,
                 tuneGrid = tune_grid,
                 tuneLength = 10, importance=TRUE)
#saveRDS(fit.xgb,paste0(res_dir,"fit.xgb.train.rds"))
```
#results 
```{r}
print(fit.xgb)
```

##importance of Variables
#interpretation with SHAP-all vars
```{r}
source("/Volumes/GoogleDrive/My Drive/AERONET-MISR/Paper#2-RSoE/aeronet/aeronet/code/XGBOOST/shap.R")
#source('~/R/Scripts/functions/shap.R')
wdb.na <- setDT(dataset)
#arrange data
names(wdb.na) <- sub("_","",names(wdb.na))
names(wdb.na) <- sub("-","",names(wdb.na))
names(wdb.na) <- sub("[","",names(wdb.na),fixed=TRUE)
names(wdb.na) <- sub("]","",names(wdb.na))
data_2 <- wdb.na[,-c("dust")]

data_dmy = dummyVars(" ~ .", data = data_2, fullRank=T)
data_x = predict(data_dmy, newdata = data_2)

## Create the xgboost model
model_xgb = xgboost(data = data_x, 
                   nround = 10, 
                   objective="reg:linear",
                   label= wdb.na$dust)  

## Calculate shap values
shap_result = shap.score.rank(xgb_model = model_xgb, 
                              X_train =data_x,
                              shap_approx = F)
###
#shap_result <- shap.values(xgb_model = model_xgb, X_train = data_x)
#shap_long <- shap.prep(xgb_model = model_xgb, X_train = data_x)
# is the same as: using given shap_contrib
#shap_long <- shap.prep(shap_contrib = shap_result$shap_score, X_train = data_x)

# **SHAP summary plot**
#shap.plot.summary(shap_long, dilute=10)
###

# `shap_approx` comes from `approxcontrib` from xgboost documentation. 
# Faster but less accurate if true. Read more: help(xgboost)

## Plot var importance based on SHAP
var_importance(shap_result, top_n=10)

## Prepare data for top N variables
shap_long <- shap.prep(shap = shap_result,
                           X_train = data_x , 
                           top_n = 10)

source('~/R/Scripts/functions/plot.shap.summary.R') #Thanks to Y.LIU (MSSM)
plot.shap.summary(shap_long)#Plot shap overall metrics
tiff(paste0(res_dir,"shap_sulfateAODINV_CA.tif"), res = 300)
plot.shap.summary(shap_long)#Plot shap overall metrics
dev.off()

## SHAP plot per variable 
# tiff(paste0(res_dir,"shap1_ca_pervar.tif"))
# xgb.plot.shap(data = data_x, # input data
#               model = model_xgb, # xgboost model
#               features = names(shap_result$mean_shap_score[1:10]), # only top 10 var
#               n_col = 3, # layout option
#               plot_loess = T # add red line to plot
#               )
# dev.off()

# Do some classical plots
#ggplotgui::ggplot_shiny(wdb.na)
```



